travis:
  secure:
    BINSTAR_TOKEN:
appveyor:
  secure:
    BINSTAR_TOKEN:

channels:
  sources:
    - loopbio
    - conda-forge
    - defaults
  targets:
    - [loopbio, main]

github:
  user_or_org: 'loopbio'
